### ISSUE TITLE
could you please help me out, thanks

### ISSUE THREAD

**Issue by BEAST-Community** [PaulApivat/tidytuesday#1]
ggplot(data = pass_in_sec, mapping = aes(x = strength, y = category, fill = category)) +
    geom_density_ridges(scale = 1.5, alpha = 0.8, quantile_lines = TRUE, quantiles = 2) + 
    theme_classic() + 
    labs(x = "Password Strength", y = "Password Category", title = "Password Category Median Strength") +
    scale_y_discrete(expand = c(0.05, 0)) + 
    theme_ridges(grid = FALSE, center = TRUE) + 
    xlim(0,15) + 
    scale_fill_manual(values = c("#543005", "#8c510a", "#bf812d", "#dfc27d", "#f6e8c3", "#c7eae5", "#80cdc1", "#35978f", "#01665e", "#003c30")) + 
    geom_text(data = pass_in_sec %>% group_by(category) %>% summarize(strength = median(strength)), aes(label=sprintf("%1.1f", strength)), position = position_nudge(y = -0.1), color = "red") + 
    theme(legend.position = "none")

Error in FUN(X[[i]], ...) : object 'category' not found

**Comment by PaulApivat** [comment]
Hi, I'd be happy to help if you could provide some context for what you need?

What code are you running?
What are you trying to achieve?
What did you expect to get?
What did you get instead?
What's not working?

Thanks!

**Comment by BEAST-Community** [comment]
for your code of password.

**Comment by BEAST-Community** [comment]
could you please reply my email, please, thanks.

**Comment by PaulApivat** [comment]
Hi, I'd be happy to help if you could provide some context for what you need?

What code are you running?

What's not working?

**Comment by BEAST-Community** [comment]
to do network analysis, like this one https://www.nature.com/articles/s41598-020-61870-x in figure 2, thanks.

**Comment by PaulApivat** [comment]
I just reformatted the code and it works; the code you posted above yield this chart:

![password_ridge](https://user-images.githubusercontent.com/4058461/128667360-14bcff69-e02b-4965-96fc-3f70deb8a8f1.png)

**Comment by BEAST-Community** [comment]
thanks
